# .github/workflows/ci-cd.yml
on:
  pull_request: {}

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]
    steps:
      - uses: actions/checkout@v4
      # Download the Databricks CLI.
      # See https://github.com/databricks/setup-cli
      - uses: databricks/setup-cli@main
      - uses: eifinger/setup-rye@v3
        id: setup-rye
        with:
          version: "0.29.0"
          cache-prefix: ${{ matrix.python-version }}
      - name: Pin python-version ${{ matrix.python-version }}
        run: rye pin ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          rye sync --no-lock
      - name: List files
        run: ls -la
      - name: Lint code
        run: rye lint
      - name: Run tests
        run: |
          source .venv/bin/activate
          rye test
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
  check-version:
    name: Check if version changed
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - name: Check if version changed
        run: |
          T=$(echo $(git diff ${{github.sha}}) | grep "pyproject.toml" | grep "+version")

          if [ -n "$T" ]; then
              echo "changed=True" >> $GITHUB_OUTPUT
          else
              echo "changed=False" >> $GITHUB_OUTPUT
          fi
  another_job:
    name: Another job
    runs-on: ubuntu-latest
    needs: check-version
    if: needs.check-version.outputs.changed == 'True'
    steps:
      - uses: actions/checkout@v4
      - name: Another job
        run: echo "Another job"
